networks:
  code-challenge-25-network-ip:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.42.0/24
          gateway: 172.21.42.1

services:
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./postgres:/var/lib/postgresql/data:rw
    networks:
      code-challenge-25-network-ip:
        ipv4_address: "172.21.42.100"

  symfony-dev:
    build:
      context: ./.docker/symfony-dev
    volumes:
      - .:/var/www/symfony/
      - symfony_app_var:/var/www/symfony/var
      - symfony_app_vendor:/var/www/symfony/vendor
    ports:
      - "42424:80"
    networks:
      code-challenge-25-network-ip:
        ipv4_address: "172.21.42.101"

volumes:
  symfony_app_var:
  symfony_app_vendor:
